#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import joblib


SCRIPT_DIR = Path(__file__).resolve().parent


def resolve_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (SCRIPT_DIR / path).resolve()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export fact-check CountVectorizer+linear SVC to Go (AC tokenizer matcher)"
    )
    parser.add_argument("--model-path", default="models/fact_check_svc.joblib")
    parser.add_argument("--output-dir", default="go-export")
    parser.add_argument("--package", default="factcheckac")
    parser.add_argument("--json-name", default="fact_check_linear_assets.json")
    parser.add_argument("--go-name", default="fact_check_ac_model.go")
    return parser.parse_args()


def go_quote(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def format_float64(value: float) -> str:
    # Use compact but precise float representation compatible with Go.
    return format(float(value), ".17g")


def extract_assets(model_path: Path) -> Tuple[List[str], List[float], float, str, str]:
    pipeline = joblib.load(model_path)

    if not hasattr(pipeline, "named_steps"):
        raise SystemExit("model is not a sklearn Pipeline")
    if "ngrams" not in pipeline.named_steps or "clf" not in pipeline.named_steps:
        raise SystemExit("pipeline must contain named steps: ngrams and clf")

    vectorizer = pipeline.named_steps["ngrams"]
    clf = pipeline.named_steps["clf"]

    if getattr(vectorizer, "binary", None) is not True:
        raise SystemExit("CountVectorizer must use binary=True")
    if getattr(vectorizer, "ngram_range", None) != (1, 1):
        raise SystemExit("Only unigram CountVectorizer is supported")
    if getattr(clf, "kernel", None) != "linear":
        raise SystemExit("Only linear SVC is supported for Go export")

    if not hasattr(clf, "coef_") or not hasattr(clf, "intercept_"):
        raise SystemExit("SVC must be trained and expose coef_/intercept_")

    classes = list(clf.classes_)
    if len(classes) != 2:
        raise SystemExit("Only binary classification is supported")

    vocab: Dict[str, int] = dict(vectorizer.vocabulary_)
    n_features = len(vocab)
    ordered_tokens = [""] * n_features
    for token, idx in vocab.items():
        if idx < 0 or idx >= n_features:
            raise SystemExit(f"invalid vocab index: {token} -> {idx}")
        ordered_tokens[idx] = token

    if any(not t for t in ordered_tokens):
        raise SystemExit("vocabulary has missing indices")

    coef = clf.coef_
    if hasattr(coef, "toarray"):
        weights = [float(x) for x in coef.toarray()[0].tolist()]
    else:
        weights = [float(x) for x in coef[0].tolist()]
    if len(weights) != n_features:
        raise SystemExit("coef dimension does not match vocabulary size")

    intercept = float(clf.intercept_[0])
    negative_label = str(classes[0])
    positive_label = str(classes[1])
    return ordered_tokens, weights, intercept, negative_label, positive_label


def write_assets_json(
    path: Path,
    tokens: List[str],
    weights: List[float],
    intercept: float,
    negative_label: str,
    positive_label: str,
) -> None:
    payload = {
        "model_type": "countvectorizer_binary_unigram_linear_svc",
        "tokens": tokens,
        "weights": weights,
        "intercept": intercept,
        "decision_rule": "score = intercept + sum(weights[i] for matched token i); score > 0 -> positive_label else negative_label",
        "negative_label": negative_label,
        "positive_label": positive_label,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def generate_go_source(
    package_name: str,
    tokens: List[str],
    weights: List[float],
    intercept: float,
    negative_label: str,
    positive_label: str,
) -> str:
    tokens_src = "\n".join(f"\t{go_quote(token)}," for token in tokens)
    weights_src = "\n".join(f"\t{format_float64(weight)}," for weight in weights)

    return f'''// Code generated by export_fact_check_to_go_ac.py; DO NOT EDIT.
package {package_name}

import (
\t"strings"
\t"unicode"
)

const NegativeLabel = {go_quote(negative_label)}
const PositiveLabel = {go_quote(positive_label)}

var modelTokens = []string{{
{tokens_src}
}}

var modelWeights = []float64{{
{weights_src}
}}

var modelIntercept = {format_float64(intercept)}

type acNode struct {{
\tnext map[rune]int
\tfail int
\tout  []int
}}

type acAutomaton struct {{
\tnodes []acNode
}}

func newACAutomaton(patterns []string) *acAutomaton {{
\ta := &acAutomaton{{nodes: []acNode{{{{next: map[rune]int{{}}}}}}}}

\tfor i, pattern := range patterns {{
\t\tstate := 0
\t\tfor _, ch := range pattern {{
\t\t\tnextState, ok := a.nodes[state].next[ch]
\t\t\tif !ok {{
\t\t\t\tnextState = len(a.nodes)
\t\t\t\ta.nodes[state].next[ch] = nextState
\t\t\t\ta.nodes = append(a.nodes, acNode{{next: map[rune]int{{}}}})
\t\t\t}}
\t\t\tstate = nextState
\t\t}}
\t\ta.nodes[state].out = append(a.nodes[state].out, i)
\t}}

\tqueue := make([]int, 0)
\tfor _, nextState := range a.nodes[0].next {{
\t\ta.nodes[nextState].fail = 0
\t\tqueue = append(queue, nextState)
\t}}

\tfor len(queue) > 0 {{
\t\tstate := queue[0]
\t\tqueue = queue[1:]

\t\tfor ch, nextState := range a.nodes[state].next {{
\t\t\tfailState := a.nodes[state].fail
\t\t\tfor failState != 0 {{
\t\t\t\tif _, ok := a.nodes[failState].next[ch]; ok {{
\t\t\t\t\tbreak
\t\t\t\t}}
\t\t\t\tfailState = a.nodes[failState].fail
\t\t\t}}

\t\t\tif to, ok := a.nodes[failState].next[ch]; ok {{
\t\t\t\ta.nodes[nextState].fail = to
\t\t\t}} else {{
\t\t\t\ta.nodes[nextState].fail = 0
\t\t\t}}

\t\t\tf := a.nodes[nextState].fail
\t\t\tif len(a.nodes[f].out) > 0 {{
\t\t\t\ta.nodes[nextState].out = append(a.nodes[nextState].out, a.nodes[f].out...)
\t\t\t}}

\t\t\tqueue = append(queue, nextState)
\t\t}}
\t}}

\treturn a
}}

func (a *acAutomaton) findMatches(text string, seen []bool) {{
\tstate := 0
\tfor _, ch := range text {{
\t\tfor state != 0 {{
\t\t\tif _, ok := a.nodes[state].next[ch]; ok {{
\t\t\t\tbreak
\t\t\t}}
\t\t\tstate = a.nodes[state].fail
\t\t}}

\t\tif to, ok := a.nodes[state].next[ch]; ok {{
\t\t\tstate = to
\t\t}} else {{
\t\t\tstate = 0
\t\t}}

\t\tif len(a.nodes[state].out) > 0 {{
\t\t\tfor _, id := range a.nodes[state].out {{
\t\t\t\tseen[id] = true
\t\t\t}}
\t\t}}
\t}}
}}

func isWordRune(r rune) bool {{
\treturn r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r)
}}

func tokenizeLowerWords(input string) []string {{
\trunes := []rune(strings.ToLower(input))
\tout := make([]string, 0, len(runes)/4)
\tstart := -1

\tflush := func(end int) {{
\t\tif start < 0 {{
\t\t\treturn
\t\t}}
\t\tif end-start >= 2 {{
\t\t\tout = append(out, string(runes[start:end]))
\t\t}}
\t\tstart = -1
\t}}

\tfor i, r := range runes {{
\t\tif isWordRune(r) {{
\t\t\tif start < 0 {{
\t\t\t\tstart = i
\t\t\t}}
\t\t\tcontinue
\t\t}}
\t\tflush(i)
\t}}
\tflush(len(runes))
\treturn out
}}

func boundaryPatterns(tokens []string) []string {{
\tpatterns := make([]string, len(tokens))
\tfor i, token := range tokens {{
\t\tpatterns[i] = " " + token + " "
\t}}
\treturn patterns
}}

var vectorizerAC = newACAutomaton(boundaryPatterns(modelTokens))

func DecisionScore(text string) float64 {{
\ttokens := tokenizeLowerWords(text)
\tif len(tokens) == 0 {{
\t\treturn modelIntercept
\t}}

\tnormalized := " " + strings.Join(tokens, " ") + " "
\tseen := make([]bool, len(modelTokens))
\tvectorizerAC.findMatches(normalized, seen)

\tscore := modelIntercept
\tfor i, ok := range seen {{
\t\tif ok {{
\t\t\tscore += modelWeights[i]
\t\t}}
\t}}
\treturn score
}}

func PredictLabel(text string) string {{
\tif DecisionScore(text) > 0 {{
\t\treturn PositiveLabel
\t}}
\treturn NegativeLabel
}}

func NeedsFactCheck(text string) bool {{
\treturn PredictLabel(text) == "needs_fact_check"
}}

func Predict(text string) (label string, needsFactCheck bool, score float64) {{
\tscore = DecisionScore(text)
\tif score > 0 {{
\t\tlabel = PositiveLabel
\t}} else {{
\t\tlabel = NegativeLabel
\t}}
\tneedsFactCheck = label == "needs_fact_check"
\treturn
}}
'''


def write_go_file(
    path: Path,
    package_name: str,
    tokens: List[str],
    weights: List[float],
    intercept: float,
    negative_label: str,
    positive_label: str,
) -> None:
    source = generate_go_source(
        package_name=package_name,
        tokens=tokens,
        weights=weights,
        intercept=intercept,
        negative_label=negative_label,
        positive_label=positive_label,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")


def main() -> None:
    args = parse_args()

    model_path = resolve_path(args.model_path)
    if not model_path.exists():
        raise SystemExit(f"model file not found: {model_path}")

    output_dir = resolve_path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    tokens, weights, intercept, negative_label, positive_label = extract_assets(model_path)

    json_path = output_dir / args.json_name
    go_path = output_dir / args.go_name

    write_assets_json(
        path=json_path,
        tokens=tokens,
        weights=weights,
        intercept=intercept,
        negative_label=negative_label,
        positive_label=positive_label,
    )
    write_go_file(
        path=go_path,
        package_name=args.package,
        tokens=tokens,
        weights=weights,
        intercept=intercept,
        negative_label=negative_label,
        positive_label=positive_label,
    )

    print(f"[ok] exported json: {json_path}")
    print(f"[ok] exported go: {go_path}")
    print(f"[info] vocab_size={len(tokens)}")
    print(f"[info] labels: negative={negative_label}, positive={positive_label}")


if __name__ == "__main__":
    main()
