#!/usr/bin/env python3
"""Export the portable jailbreak L1 JSON model as a Go source asset."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_MODEL = SCRIPT_DIR.parent / "models" / "jailbreak_linear_token.json"
DEFAULT_OUTPUT = (
    SCRIPT_DIR.parent.parent
    / "semantic-router"
    / "pkg"
    / "classification"
    / "jailbreaklinearsvm"
    / "model.go"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export jailbreak L1 JSON as Go source")
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def go_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    args = parse_args()
    model = json.loads(args.model.read_text(encoding="utf-8"))
    tokens = model["tokens"]
    weights = model["weights"]
    if len(tokens) != len(weights) or not tokens:
        raise SystemExit("model tokens and weights must be non-empty and have equal length")

    token_lines = "\n".join(f"\t{go_quote(token)}," for token in tokens)
    weight_lines = "\n".join(f"\t{float(weight):.17g}," for weight in weights)
    source = f'''// Code generated by export_linear_jailbreak_to_go.py; DO NOT EDIT.
package jailbreaklinearsvm

import "github.com/vllm-project/semantic-router/src/semantic-router/pkg/classification/lineartoken"

func Model() lineartoken.Model {{
	return lineartoken.Model{{
		Tokens:        modelTokens,
		Weights:       modelWeights,
		Intercept:     modelIntercept,
		NegativeLabel: {go_quote(model["negative_label"])},
		PositiveLabel: {go_quote(model["positive_label"])},
	}}
}}

var modelTokens = []string{{
{token_lines}
}}

var modelWeights = []float64{{
{weight_lines}
}}

const modelIntercept = {float(model["intercept"]):.17g}
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()